networks:
  dev:

services:
  db:
    image: postgres:16
    container_name: db
    command: -p 5454
    env_file:
      - .env-non-dev
    volumes:
      - data-volume:/var/lib/postgresql/TASK/data
    networks:
      - dev

  backend:
    build:
      context: ./backend
    env_file:
      - .env-non-dev
    container_name: TASK_fastapi_app
    command: ["/TASK_fastapi_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - dev
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env-non-dev
    ports:
      - 5050:80
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx_subdomain.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

volumes:
  data-volume: